export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const DATA_LOADING = 'DATA_LOADING';

export const FETCH_ALL_FEEDS = 'FETCH_ALL_FEEDS';
export const FETCH_ALL_FEEDS_SUCCESS = 'FETCH_ALL_FEEDS_SUCCESS';

export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS';
export const FETCH_ALL_TOPICS_SUCCESS = 'FETCH_ALL_TOPICS_SUCCESS';

export const CHANGE_NET_INFO = 'CHANGE_NET_INFO';
