export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const DATA_LOADING = 'DATA_LOADING';

export const FETCH_ALL_FEEDS = 'FETCH_ALL_FEEDS';
export const FETCH_ALL_FEEDS_SUCCESS = 'FETCH_ALL_FEEDS_SUCCESS';

export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS';
export const FETCH_ALL_TOPICS_SUCCESS = 'FETCH_ALL_TOPICS_SUCCESS';

export const FETCH_ALL_DOMAIN = 'FETCH_ALL_DOMAIN';
export const FETCH_ALL_DOMAIN_SUCCESS = 'FETCH_ALL_DOMAIN_SUCCESS';
export const SEARCH_DOMAIN = 'SEARCH_DOMAIN';
export const SEARCH_DOMAIN_SUCCESS = 'SEARCH_DOMAIN_SUCCESS';

export const CHANGE_NET_INFO = 'CHANGE_NET_INFO';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';

export const CHOOSE_GENDER = 'CHOOSE_GENDER';
export const UPDATE_GENDER = 'UPDATE_GENDER';

export const FETCH_ALL_CLUSTER = 'FETCH_ALL_CLUSTER';
export const FETCH_ALL_CLUSTER_SUCCESS = 'FETCH_ALL_CLUSTER_SUCCESS';

export const FETCH_ALL_COVER = 'FETCH_ALL_COVER';
export const FETCH_ALL_COVER_SUCCESS = 'FETCH_ALL_COVER_SUCCESS';
